
# LABEL OF THE PROPERTIES
PROP_LABEL_REGION = "region"
PROP_LABEL_DEPARTEMENT = "departement"
PROP_LABEL_CITY = "city"
PROP_LABEL_POSTCODE = "postcode"
PROP_LABEL_ADDRESS = "address"

PROP_LABEL_NAME = "name"

PROP_LABEL_PRECISION_ON_PROTECTION = "precision_on_the_protection"
PROP_LABEL_DATE_OF_PROTECTION = "date_of_protection"
PROP_LABEL_HISTORIQUE = "historique"
PROP_LABEL_LOCATION = "location"
PROP_LABEL_SIECLE = "siecle"
PROP_LABEL_STATUT = "statut"

PROP_LABEL_CONTACT = "contact" 
PROP_LABEL_PHONE = "phone"
PROP_LABEL_WEBSITE = "website"

# VALUE OF THE PROPERTIES
PROP_VALUE_STRING = "StringValue"
PROP_VALUE_URL = "UrlValue"
PROP_VALUE_COORDINATE = "GeoLocation"

# DESCRIPTION OF THE ITEM
ITEM_DESCRIPTION = "description"